inherit_from:
  - .rubocop_todo.yml
  - .rubocop_dnsimple.yml

# [codesmell]
# It's irrelevant here, but it could be a code smell.
# Hence keep it disabled, but don't include it in the DNSimple suite.
Lint/Loop:
  Enabled: false
